apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-default-backend
  namespace: ingress-nginx
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
        <title>Kubrix Services</title>
        <style>
            body {
                font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
                max-width: 800px;
                margin: 50px auto;
                padding: 20px;
                background: #f5f5f5;
            }
            .container {
                background: white;
                padding: 30px;
                border-radius: 10px;
                box-shadow: 0 2px 10px rgba(0,0,0,0.1);
            }
            h1 { color: #333; margin-bottom: 10px; }
            .subtitle { color: #666; margin-bottom: 30px; }
            .services {
                display: grid;
                grid-template-columns: repeat(auto-fit, minmax(250px, 1fr));
                gap: 20px;
                margin-top: 30px;
            }
            .service {
                background: #f8f9fa;
                padding: 20px;
                border-radius: 8px;
                border: 1px solid #e9ecef;
                text-decoration: none;
                color: #333;
                transition: all 0.3s;
            }
            .service:hover {
                transform: translateY(-2px);
                box-shadow: 0 4px 12px rgba(0,0,0,0.1);
                border-color: #007bff;
            }
            .service h3 { margin: 0 0 10px 0; color: #007bff; }
            .service p { margin: 0; color: #666; font-size: 14px; }
            .status { 
                display: inline-block;
                padding: 2px 8px;
                border-radius: 4px;
                font-size: 12px;
                margin-left: 10px;
            }
            .active { background: #d4edda; color: #155724; }
            .partial { background: #fff3cd; color: #856404; }
            .note {
                background: #e3f2fd;
                padding: 15px;
                border-radius: 5px;
                margin-top: 30px;
                color: #1565c0;
            }
            code {
                background: #f1f3f4;
                padding: 2px 6px;
                border-radius: 3px;
                font-family: monospace;
            }
        </style>
    </head>
    <body>
        <div class="container">
            <h1>🚀 Kubrix Platform Services</h1>
            <p class="subtitle">Click a service below or use the direct URLs with proper Host headers</p>
            
            <div class="services">
                <a href="http://localhost:8080" class="service">
                    <h3>ArgoCD <span class="status active">Active</span></h3>
                    <p>GitOps continuous deployment platform</p>
                    <p style="margin-top: 10px;"><code>localhost:8080</code></p>
                </a>
                
                <a href="http://localhost:3000" class="service">
                    <h3>Grafana <span class="status active">Active</span></h3>
                    <p>Monitoring and observability dashboards</p>
                    <p style="margin-top: 10px;"><code>localhost:3000</code></p>
                </a>
                
                <a href="http://backstage.kubrix.local:30404" class="service">
                    <h3>Backstage <span class="status active">Active</span></h3>
                    <p>Developer portal (fully operational)</p>
                    <p style="margin-top: 10px;"><code>backstage.kubrix.local:30404</code></p>
                </a>
                
                <div class="service" style="opacity: 0.6">
                    <h3>Keycloak <span class="status partial">Not Ready</span></h3>
                    <p>Identity and access management</p>
                    <p style="margin-top: 10px;"><code>keycloak.kubrix.local</code></p>
                </div>
                
                <div class="service" style="opacity: 0.6">
                    <h3>Vault <span class="status partial">Not Ready</span></h3>
                    <p>Secrets management</p>
                    <p style="margin-top: 10px;"><code>vault.kubrix.local</code></p>
                </div>
                
                <div class="service" style="opacity: 0.6">
                    <h3>Kargo <span class="status partial">Not Ready</span></h3>
                    <p>Progressive delivery</p>
                    <p style="margin-top: 10px;"><code>kargo.kubrix.local</code></p>
                </div>
            </div>
            
            <div class="note">
                <strong>Note:</strong> To access services via their domain names, you need to set the Host header. 
                For example: <code>curl -H "Host: backstage.kubrix.local" http://localhost:8880</code>
                <br><br>
                <strong>Backstage Access:</strong> Use <code>http://backstage.kubrix.local:30404</code> directly in your browser.
                <br><br>
                <strong>Blank Page Issue?</strong> If Backstage shows a blank page, try:
                <ul style="margin: 10px 0;">
                    <li>Hard refresh (Ctrl+Shift+R or Cmd+Shift+R)</li>
                    <li>Clear browser cache</li>
                    <li>Try a different browser</li>
                    <li>Check browser console for JavaScript errors</li>
                </ul>
            </div>
        </div>
    </body>
    </html>